### ISSUE TITLE
Add User unsuccessful without "answers" in payload

### ISSUE THREAD

**Issue by manue1** [evalvarez12/cc-user-api#1]
When adding a user the "answers" should be optional.

However - POST to /user with following parameters:
`{
  "first_name": "Thomas",
  "last_name" : "Test",
  "email" : "test@test.testy",
  "password": "juanito"
}`

returns:
`{
  "success": false,
  "error": "sql: converting Exec argument #0's type: unexpected end of JSON input"
}`

I had a look in the Validate function and it doesn't list answers as required, so not sure why this error comes up.

**Comment by evalvarez12** [comment]
Fixed. Now when adding a user without "answers", they will be set to the empty JSON  `{}`.
